CREATE ROLE lp LOGIN
    NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

ALTER ROLE lp PASSWORD 'lp';

CREATE DATABASE lp
    WITH OWNER = lp
    TEMPLATE = template0
    ENCODING = 'UTF8'
    LC_COLLATE = 'en_US.UTF-8'
    LC_CTYPE = 'en_US.UTF-8'
    CONNECTION LIMIT = -1;

ALTER DATABASE lp OWNER TO lp;
