version: "3.3"
networks:
  lp-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.7.0/24

services:
  lp-postgres:
    container_name: "lp-postgres"
    image: lp/postgres
    build: .
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - "5432"
    networks:
      lp-network:
        ipv4_address: 172.19.7.103
        aliases:
          - postgres.lp.lo
volumes:
  pgdata:
